name: Build ImageGlass

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore & Publish ImageGlass
        run: >
          msbuild v9/ImageGlass/ImageGlass.csproj
          -restore
          -t:Publish
          -p:Configuration=Release
          -p:Platform=x64
          -p:RuntimeIdentifier=win-x64
          -p:SelfContained=true
          -p:PublishSingleFile=false
          -p:PublishDir=${{ github.workspace }}\publish\

      - name: Restore & Publish igcmd
        run: >
          msbuild v9/igcmd/igcmd.csproj
          -restore
          -t:Publish
          -p:Configuration=Release
          -p:Platform=x64
          -p:RuntimeIdentifier=win-x64
          -p:SelfContained=true
          -p:PublishSingleFile=false
          -p:PublishDir=${{ github.workspace }}\publish\

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImageGlass-win-x64
          path: ./publish
